### ISSUE TITLE
Auto-format contributions with Black

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#20]
As suggested by @alin23 in #18, consider setting up [Black](https://github.com/ambv/black) to save everyone's time on style and formatting.

Possible implementation using [pre-commit](https://pre-commit.com/):

```yaml
repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.2.0
  hooks:
  - id: seed-isort-config
    args: [--exclude=tests/.+\.py]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
- repo: local
  hooks:
  - id: pylint
    name: pylint
    stages: [push]
    entry: pylint
    language: system
    types: [python]
- repo: local
  hooks:
  - id: pytest
    name: pytest
    stages: [push]
    entry: pytest
    language: system
    pass_filenames: false
    types: [python]
```

> This does the following:
>
> - On commit
>   - formats code
>   - sorts imports
> - On push
>   - analyzes code with pylint
runs tests using pytest
